### ISSUE TITLE
need your dataset

### ISSUE THREAD

**Issue by Scorpio-m7** [kt4ngw/fedavg-pytorch#1]
Error occurred during Execute  data.py, missing dataset
need "./data/MNIST/raw/train-images-idx3-ubyte.gz"
        data_dir = r'./data/MNIST/raw'
        train_images_path = os.path.join(data_dir, 'train-images-idx3-ubyte.gz')
        train_labels_path = os.path.join(data_dir, 'train-labels-idx1-ubyte.gz')
        test_images_path = os.path.join(data_dir, 't10k-images-idx3-ubyte.gz')
        test_labels_path = os.path.join(data_dir, 't10k-labels-idx1-ubyte.gz')

**Comment by kt4ngw** [comment]
Sorry! Not responding to your issue promptly.
The current version has uploaded the MNIST dataset and modified the copy problem of model parameters. Since MNIST dataset is open source it was not previously uploaded the dataset.
Thank you for visiting the repository and asking the question.
